import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Midnight Bloom Chiffon",
    price: 18500,
    category: "Unstitched",
    subCategory: "Luxury Chiffon",
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617175548923-380f3cdb0ba0?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "An exquisite midnight blue chiffon ensemble featuring intricate gold tilla work and hand-placed sequins. The dupatta is finished with delicate scalloped edges.",
    fabric: "Pure Chiffon shirt and dupatta, Raw Silk trousers.",
    care: ["Dry clean only", "Do not bleach", "Iron at low temperature"],
    isNew: true,
    isLuxury: true,
    colors: ["Midnight Blue", "Gold"],
    sizes: ["Unstitched"],
  },
  {
    id: "2",
    name: "Ivory Grace Kurta",
    price: 8900,
    category: "Ready to Wear",
    subCategory: "Kurtas",
    images: [
      "https://images.unsplash.com/photo-1595991209266-5ff5a3a2f008?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A classic ivory kurta with contemporary cutwork details on the sleeves and hem. Perfect for summer afternoons.",
    fabric: "Premium Pima Cotton",
    care: ["Hand wash cold", "Dry in shade", "Warm iron"],
    isNew: true,
    colors: ["Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "3",
    name: "Crimson Velvet Festive",
    price: 45000,
    category: "Luxury Formals",
    subCategory: "Wedding Wear",
    images: [
      "https://images.unsplash.com/photo-1621184455862-c163dfb30e0f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A majestic crimson velvet peshwas adorned with traditional zardozi and dabka work. A true masterpiece for the wedding season.",
    fabric: "Micro Velvet shirt, Jamawar lehenga, Net dupatta.",
    care: ["Professional dry clean only", "Store in a muslin bag"],
    isLuxury: true,
    colors: ["Crimson Red"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "4",
    name: "Emerald Silk Co-ords",
    price: 12500,
    category: "Ready to Wear",
    subCategory: "Co-ords",
    images: [
      "https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Minimalist emerald green silk co-ord set with a relaxed fit and button-down detail. Effortlessly chic.",
    fabric: "Pure Crepe Silk",
    care: ["Dry clean recommended", "Steam iron only"],
    isNew: true,
    colors: ["Emerald Green"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "5",
    name: "Pastel Dream Lawn",
    price: 6500,
    category: "Unstitched",
    subCategory: "Lawn",
    images: [
      "https://images.unsplash.com/photo-1605763240000-7e93b172d754?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1604176354204-9268737828e4?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Soft pastel floral prints on breathable lawn fabric. Comes with a printed chiffon dupatta.",
    fabric: "Digital Printed Lawn",
    care: ["Machine wash gentle", "Iron at medium heat"],
    colors: ["Pastel Pink", "Mint"],
    sizes: ["Unstitched"],
  },
  {
    id: "6",
    name: "Golden Hour Jhumkas",
    price: 4500,
    category: "Accessories",
    subCategory: "Jewelry",
    images: [
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535633302704-b04201c88d80?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Traditional gold-plated jhumkas with pearl drops and intricate filigree work.",
    fabric: "Gold Plated Brass",
    care: ["Avoid contact with perfume", "Store in airtight box"],
    colors: ["Gold"],
    sizes: ["One Size"],
  },
  {
    id: "7",
    name: "Rose Garden Silk",
    price: 15500,
    category: "Unstitched",
    subCategory: "Silk",
    images: [
      "https://images.unsplash.com/photo-1617175548923-380f3cdb0ba0?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Lustrous pure silk fabric with a delicate rose garden print. Perfect for evening soirees.",
    fabric: "100% Pure Silk",
    care: ["Dry clean only", "Iron on silk setting"],
    colors: ["Rose Pink"],
    sizes: ["Unstitched"],
  },
  {
    id: "8",
    name: "Azure 2-Piece Set",
    price: 11200,
    category: "Ready to Wear",
    subCategory: "2-Piece",
    images: [
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595991209266-5ff5a3a2f008?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A vibrant azure blue 2-piece set featuring a straight kurta and matching culottes with lace inserts.",
    fabric: "Viscose Linen",
    care: ["Hand wash cold", "Line dry"],
    colors: ["Azure Blue"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "9",
    name: "Floral Festive 3-Piece",
    price: 16800,
    category: "Ready to Wear",
    subCategory: "3-Piece",
    images: [
      "https://images.unsplash.com/photo-1604176354204-9268737828e4?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605763240000-7e93b172d754?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A complete 3-piece ready-to-wear ensemble with a heavily embroidered shirt, plain trousers, and an organza dupatta.",
    fabric: "Cotton Karandi",
    care: ["Dry clean only"],
    isLuxury: true,
    colors: ["Mustard Yellow"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "10",
    name: "Little Princess Lehenga",
    price: 7500,
    category: "Kids",
    subCategory: "Girls' Eastern Wear",
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1621184455862-c163dfb30e0f?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Adorable miniature lehenga choli for your little one, featuring soft embroidery and a net dupatta.",
    fabric: "Soft Silk and Net",
    care: ["Dry clean only"],
    colors: ["Peach"],
    sizes: ["2-4Y", "4-6Y", "6-8Y"],
  },
  {
    id: "11",
    name: "Midnight Suede Bag",
    price: 5200,
    category: "Accessories",
    subCategory: "Bags",
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1591561954557-26941169b49e?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Handcrafted suede clutch with a gold chain strap and traditional embroidery.",
    fabric: "Genuine Suede",
    care: ["Wipe with dry cloth"],
    colors: ["Black"],
    sizes: ["One Size"],
  },
  {
    id: "12",
    name: "Oud Al US BRIDALS Perfume",
    price: 3800,
    category: "Accessories",
    subCategory: "Perfumes",
    images: [
      "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A signature scent featuring notes of pure oud, saffron, and sandalwood. Long-lasting and luxurious.",
    fabric: "Fragrance Oil",
    care: ["Store in cool place"],
    colors: ["Clear"],
    sizes: ["50ml"],
  },
  {
    id: "13",
    name: "Classic Cotton Unstitched",
    price: 4200,
    category: "Unstitched",
    subCategory: "Cotton",
    images: [
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "High-quality premium cotton for everyday comfort. Includes shirt and trouser pieces.",
    fabric: "100% Egyptian Cotton",
    care: ["Machine wash cold"],
    colors: ["Slate Grey", "Navy"],
    sizes: ["Unstitched"],
  },
  {
    id: "14",
    name: "Festive Glow Kurta",
    price: 9500,
    category: "Ready to Wear",
    subCategory: "Kurtas",
    images: [
      "https://images.unsplash.com/photo-1535633302704-b04201c88d80?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A glowing yellow kurta with mirror work on the neckline. Ideal for festive gatherings.",
    fabric: "Silk Blend",
    care: ["Dry clean only"],
    isNew: true,
    colors: ["Yellow"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "15",
    name: "Royal Velvet Shawl",
    price: 12000,
    category: "Accessories",
    subCategory: "Jewelry", // Using Jewelry as a catch-all for now or I could add Shawls
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1621184455862-c163dfb30e0f?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Deep maroon velvet shawl with heavy gold tilla embroidery on all four sides.",
    fabric: "Micro Velvet",
    care: ["Dry clean only"],
    colors: ["Maroon"],
    sizes: ["One Size"],
  },
  {
    id: "16",
    name: "Summer Breeze Lawn",
    price: 5800,
    category: "Unstitched",
    subCategory: "Lawn",
    images: [
      "https://images.unsplash.com/photo-1604176354204-9268737828e4?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605763240000-7e93b172d754?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Cool and comfortable lawn with a refreshing blue floral print. Includes a voile dupatta.",
    fabric: "Premium Lawn",
    care: ["Machine wash cold"],
    colors: ["Light Blue"],
    sizes: ["Unstitched"],
  },
  {
    id: "17",
    name: "Pearl Embellished 2-Piece",
    price: 13500,
    category: "Ready to Wear",
    subCategory: "2-Piece",
    images: [
      "https://images.unsplash.com/photo-1595991209266-5ff5a3a2f008?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Elegant 2-piece set with pearl embellishments on the neckline and sleeves. Perfect for formal dinners.",
    fabric: "Raw Silk",
    care: ["Dry clean only"],
    isLuxury: true,
    colors: ["Champagne"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "18",
    name: "Gilded Rose Festive",
    price: 32000,
    category: "Luxury Formals",
    subCategory: "Festive Collections",
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617175548923-380f3cdb0ba0?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A stunning festive ensemble in rose gold with intricate tilla and sequin work. Comes with a heavy dupatta.",
    fabric: "Organza and Silk",
    care: ["Professional dry clean only"],
    isLuxury: true,
    colors: ["Rose Gold"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "19",
    name: "Tiny Tots Kurta Set",
    price: 4800,
    category: "Kids",
    subCategory: "Girls' Eastern Wear",
    images: [
      "https://images.unsplash.com/photo-1604176354204-9268737828e4?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605763240000-7e93b172d754?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Comfortable cotton kurta set for girls with soft lace details and matching trousers.",
    fabric: "Soft Cotton",
    care: ["Machine wash gentle"],
    colors: ["Lavender"],
    sizes: ["2-4Y", "4-6Y", "6-8Y", "8-10Y"],
  },
  {
    id: "20",
    name: "Silver Filigree Earrings",
    price: 2800,
    category: "Accessories",
    subCategory: "Jewelry",
    images: [
      "https://images.unsplash.com/photo-1535633302704-b04201c88d80?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Delicate silver filigree earrings with a vintage finish. Lightweight and elegant.",
    fabric: "Sterling Silver Finish",
    care: ["Keep away from moisture"],
    colors: ["Silver"],
    sizes: ["One Size"],
  }
];
